#just for tac
statistics=true
job=dim_equipement
jobVersion=0.1
date=2026-04-29 023153120
contextName=Default
jobId=_Xwp0YC1qEfGaQY69YFDL7Q
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=DW_PADEL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=