#just for tac
statistics=true
job=dim_tournament
jobVersion=0.1
date=2026-04-29 022411161
contextName=Default
jobId=_7Q82kBeREfGON_BXaH-SkA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=DW_PADEL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=