#just for tac
statistics=true
job=FACT_MATCHS
jobVersion=0.1
date=2026-04-29 022424235
contextName=Default
jobId=_PAhVoC6VEfGLXpzg26dSlw
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=DW_PADEL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=