#just for tac
statistics=true
job=dim_player
jobVersion=0.1
date=2026-04-29 022400503
contextName=Default
jobId=_O0wqkBZ4EfGzB5paIwtWEA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=DW_PADEL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=