#just for tac
statistics=true
job=matchs
jobVersion=0.1
date=2026-04-29 021807969
contextName=Default
jobId=_Dr1IgDG6EfGqJekMovSDxg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=DW_PADEL
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=