"""
Generate data/*.csv fallbacks for model-service when SQL Server is unavailable.
Run from repo root:  python scripts/build_data_fallback.py

Matches frontend mockData.js MATCHES + MONTHLY_VIEWS so the UI stays consistent
when GET /api/analytics/overview uses CSV instead of dbo.matches_with_views_interactions.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

# Mirrors frontend/src/data/mockData.js — MATCHES (warehouse column names)
MATCH_ROWS: list[dict[str, object]] = [
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Final",
        "date": "2024-11-17",
        "winner": "",
        "team1_player1_name": "Arturo Coello",
        "team1_player2_name": "Agustín Tapia",
        "team2_player1_name": "Juan Lebrón",
        "team2_player2_name": "Alejandro Galán",
        "views": 245000,
        "interactions": 38500,
        "aces_t1": 8,
        "aces_t2": 5,
        "double_faults_t1": 3,
        "double_faults_t2": 4,
        "won_on_1st_serve_t1": 78,
        "won_on_1st_serve_t2": 71,
        "won_on_2nd_serve_t1": 54,
        "won_on_2nd_serve_t2": 49,
        "total_points_won_t1": 125,
        "total_points_won_t2": 98,
        "break_points_converted_t1": 5,
        "break_points_converted_t2": 2,
        "total_won_on_return_t1": 42,
        "total_won_on_return_t2": 33,
    },
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Semifinal",
        "date": "2024-11-15",
        "winner": "team_1",
        "team1_player1_name": "Arturo Coello",
        "team1_player2_name": "Agustín Tapia",
        "team2_player1_name": "Federico Chingotto",
        "team2_player2_name": "Juan Tello",
        "views": 198000,
        "interactions": 31200,
        "aces_t1": 10,
        "aces_t2": 4,
        "double_faults_t1": 2,
        "double_faults_t2": 6,
        "won_on_1st_serve_t1": 81,
        "won_on_1st_serve_t2": 65,
        "won_on_2nd_serve_t1": 58,
        "won_on_2nd_serve_t2": 44,
        "total_points_won_t1": 135,
        "total_points_won_t2": 82,
        "break_points_converted_t1": 7,
        "break_points_converted_t2": 1,
        "total_won_on_return_t1": 48,
        "total_won_on_return_t2": 28,
    },
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Semifinal",
        "date": "2024-11-15",
        "winner": "team_1",
        "team1_player1_name": "Juan Lebrón",
        "team1_player2_name": "Alejandro Galán",
        "team2_player1_name": "Franco Stupaczuk",
        "team2_player2_name": "Martín Di Nenno",
        "views": 176000,
        "interactions": 28900,
        "aces_t1": 6,
        "aces_t2": 7,
        "double_faults_t1": 3,
        "double_faults_t2": 5,
        "won_on_1st_serve_t1": 74,
        "won_on_1st_serve_t2": 69,
        "won_on_2nd_serve_t1": 52,
        "won_on_2nd_serve_t2": 47,
        "total_points_won_t1": 148,
        "total_points_won_t2": 130,
        "break_points_converted_t1": 4,
        "break_points_converted_t2": 3,
        "total_won_on_return_t1": 61,
        "total_won_on_return_t2": 45,
    },
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Quarterfinal",
        "date": "2024-11-13",
        "winner": "team_1",
        "team1_player1_name": "Arturo Coello",
        "team1_player2_name": "Agustín Tapia",
        "team2_player1_name": "Sanyo Gutiérrez",
        "team2_player2_name": "Matías Díaz",
        "views": 142000,
        "interactions": 22800,
        "aces_t1": 12,
        "aces_t2": 2,
        "double_faults_t1": 1,
        "double_faults_t2": 7,
        "won_on_1st_serve_t1": 84,
        "won_on_1st_serve_t2": 61,
        "won_on_2nd_serve_t1": 61,
        "won_on_2nd_serve_t2": 40,
        "total_points_won_t1": 118,
        "total_points_won_t2": 64,
        "break_points_converted_t1": 8,
        "break_points_converted_t2": 0,
        "total_won_on_return_t1": 52,
        "total_won_on_return_t2": 21,
    },
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Quarterfinal",
        "date": "2024-11-13",
        "winner": "team_1",
        "team1_player1_name": "Juan Lebrón",
        "team1_player2_name": "Alejandro Galán",
        "team2_player1_name": "Álvaro Cepero",
        "team2_player2_name": "Lucho Capra",
        "views": 134000,
        "interactions": 19700,
        "aces_t1": 5,
        "aces_t2": 8,
        "double_faults_t1": 4,
        "double_faults_t2": 5,
        "won_on_1st_serve_t1": 72,
        "won_on_1st_serve_t2": 68,
        "won_on_2nd_serve_t1": 50,
        "won_on_2nd_serve_t2": 46,
        "total_points_won_t1": 141,
        "total_points_won_t2": 118,
        "break_points_converted_t1": 4,
        "break_points_converted_t2": 3,
        "total_won_on_return_t1": 58,
        "total_won_on_return_t2": 39,
    },
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Quarterfinal",
        "date": "2024-11-13",
        "winner": "team_1",
        "team1_player1_name": "Federico Chingotto",
        "team1_player2_name": "Juan Tello",
        "team2_player1_name": "Alex Ruiz",
        "team2_player2_name": "Edu Alonso",
        "views": 98000,
        "interactions": 14200,
        "aces_t1": 6,
        "aces_t2": 4,
        "double_faults_t1": 3,
        "double_faults_t2": 5,
        "won_on_1st_serve_t1": 74,
        "won_on_1st_serve_t2": 67,
        "won_on_2nd_serve_t1": 51,
        "won_on_2nd_serve_t2": 44,
        "total_points_won_t1": 122,
        "total_points_won_t2": 89,
        "break_points_converted_t1": 5,
        "break_points_converted_t2": 1,
        "total_won_on_return_t1": 47,
        "total_won_on_return_t2": 31,
    },
    {
        "tournament_name": "FIP World Padel Championship",
        "round": "Quarterfinal",
        "date": "2024-11-13",
        "winner": "team_1",
        "team1_player1_name": "Franco Stupaczuk",
        "team1_player2_name": "Martín Di Nenno",
        "team2_player1_name": "Sanyo Gutiérrez",
        "team2_player2_name": "Matías Díaz",
        "views": 112000,
        "interactions": 17500,
        "aces_t1": 9,
        "aces_t2": 3,
        "double_faults_t1": 4,
        "double_faults_t2": 3,
        "won_on_1st_serve_t1": 71,
        "won_on_1st_serve_t2": 74,
        "won_on_2nd_serve_t1": 48,
        "won_on_2nd_serve_t2": 53,
        "total_points_won_t1": 131,
        "total_points_won_t2": 109,
        "break_points_converted_t1": 6,
        "break_points_converted_t2": 2,
        "total_won_on_return_t1": 43,
        "total_won_on_return_t2": 62,
    },
    {
        "tournament_name": "Premier Padel P1 Doha",
        "round": "Final",
        "date": "2024-10-08",
        "winner": "team_1",
        "team1_player1_name": "Arturo Coello",
        "team1_player2_name": "Agustín Tapia",
        "team2_player1_name": "Federico Chingotto",
        "team2_player2_name": "Juan Tello",
        "views": 312000,
        "interactions": 48900,
        "aces_t1": 11,
        "aces_t2": 5,
        "double_faults_t1": 2,
        "double_faults_t2": 5,
        "won_on_1st_serve_t1": 80,
        "won_on_1st_serve_t2": 68,
        "won_on_2nd_serve_t1": 57,
        "won_on_2nd_serve_t2": 46,
        "total_points_won_t1": 128,
        "total_points_won_t2": 94,
        "break_points_converted_t1": 6,
        "break_points_converted_t2": 2,
        "total_won_on_return_t1": 50,
        "total_won_on_return_t2": 36,
    },
    {
        "tournament_name": "Premier Padel P1 Doha",
        "round": "Semifinal",
        "date": "2024-10-06",
        "winner": "team_1",
        "team1_player1_name": "Arturo Coello",
        "team1_player2_name": "Agustín Tapia",
        "team2_player1_name": "Juan Lebrón",
        "team2_player2_name": "Alejandro Galán",
        "views": 224000,
        "interactions": 35600,
        "aces_t1": 7,
        "aces_t2": 4,
        "double_faults_t1": 4,
        "double_faults_t2": 3,
        "won_on_1st_serve_t1": 74,
        "won_on_1st_serve_t2": 75,
        "won_on_2nd_serve_t1": 51,
        "won_on_2nd_serve_t2": 54,
        "total_points_won_t1": 143,
        "total_points_won_t2": 127,
        "break_points_converted_t1": 4,
        "break_points_converted_t2": 3,
        "total_won_on_return_t1": 55,
        "total_won_on_return_t2": 63,
    },
]

# MONTHLY_VIEWS mock (year, month number, total_views, match_count)
MONTHLY_ROWS: list[tuple[int, int, int, int]] = [
    (2024, 1, 1_240_000, 18),
    (2024, 2, 1_580_000, 22),
    (2024, 3, 2_140_000, 31),
    (2024, 4, 1_890_000, 27),
    (2024, 5, 2_450_000, 35),
    (2024, 6, 2_980_000, 42),
    (2024, 7, 3_750_000, 51),
    (2024, 8, 3_210_000, 44),
    (2024, 9, 4_120_000, 58),
    (2024, 10, 4_890_000, 63),
    (2024, 11, 5_640_000, 71),
    (2024, 12, 6_100_000, 80),
]


def main() -> None:
    DATA.mkdir(parents=True, exist_ok=True)

    match_cols = list(MATCH_ROWS[0].keys())
    matches_path = DATA / "matches_with_views_interactions.csv"
    with matches_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=match_cols)
        w.writeheader()
        for row in MATCH_ROWS:
            w.writerow(row)

    monthly_path = DATA / "monthly_views.csv"
    with monthly_path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["year", "month", "total_views", "match_count"])
        for yr, mo, tv, mc in MONTHLY_ROWS:
            w.writerow([yr, mo, tv, mc])

    print(f"Wrote {matches_path} ({len(MATCH_ROWS)} rows)")
    print(f"Wrote {monthly_path} ({len(MONTHLY_ROWS)} rows)")


if __name__ == "__main__":
    main()
